In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r"C:\Users\DeLL\Documents\Python Files\Stats and ML by Garvit\ML\Linear Regression\Linear Regression\Advertising.csv",index_col=0)
df.head()

TV  Radio  Newspaper  Sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [5]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1:].values

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [11]:
x_train.shape

(140, 3)

In [12]:
y_train.shape

(140, 1)

In [13]:
x_test.shape

(60, 3)

In [14]:
y_test.shape

(60, 1)

In [18]:
lasso = Lasso()
model_l = lasso.fit(x_train,y_train)

In [19]:
y_pred = model_l.predict(x_test)
y_pred

array([ 7.02315716,  8.42483964, 13.78994086,  6.29944116, 14.82307076,
       16.35487811, 13.58427654, 17.97229701, 12.13730284, 12.34276347,
       18.13075881, 16.3932335 , 24.51973776,  9.06286949, 15.26782783,
       10.16383529, 20.30463033, 13.92481814,  4.82275092, 14.91049294,
       10.61272448, 18.26036224,  9.93842789, 14.11911828, 23.93890073,
       12.80011201, 12.16778034, 15.59049756, 10.32635571, 18.63139737,
       18.79155521, 11.51584496, 17.19296017,  9.96978605,  5.52042888,
       19.14166721, 23.63769387, 20.48432428, 13.43716105, 21.49291448,
       15.17737219, 16.34065798, 14.98959924,  8.66600135, 19.33895484,
       10.29727206, 21.9168001 , 10.62744461, 19.86799142, 10.01893158,
        9.3378534 ,  8.39304348, 15.80711285, 14.99910229, 12.49200273,
       16.83949307, 16.8540768 , 13.03687723, 11.4966207 , 18.5448055 ])

In [20]:
model_l.coef_

array([0.04506992, 0.17798861, 0.00180775])

In [29]:
from sklearn.metrics import r2_score,mean_squared_error,roc_curve,roc_auc_score,auc

In [23]:
rscore = r2_score(y_test,y_pred)
rscore

0.9043917403954406

In [24]:
df.shape

(200, 4)

In [25]:
adjr = 1-((1-rscore)*(199)/(196))
adjr

0.9029283486667994

In [26]:
mse = mean_squared_error(y_test,y_pred)
mse

2.6133678534849785

In [27]:
rmse = np.sqrt(mse)
rmse

1.6165914305986464

In [31]:
from sklearn.linear_model import Ridge

In [34]:
ridge = Ridge()

In [36]:
model_r = ridge.fit(x_train,y_train)

In [37]:
y_pred = model_r.predict(x_test)
y_pred

array([[ 6.98107678],
       [ 8.385159  ],
       [13.79058973],
       [ 6.24370885],
       [14.78775217],
       [16.37441638],
       [13.65190388],
       [17.90262909],
       [12.05667186],
       [12.41712186],
       [18.17791904],
       [16.3635072 ],
       [24.63696643],
       [ 9.0309044 ],
       [15.19093062],
       [10.09757471],
       [20.36564088],
       [13.86416989],
       [ 4.74588699],
       [14.83757732],
       [10.55361551],
       [18.30230366],
       [ 9.83233039],
       [14.05104428],
       [24.04234929],
       [12.69901083],
       [12.20727421],
       [15.69361298],
       [10.31490695],
       [18.57128235],
       [18.74992327],
       [11.50199903],
       [17.21929595],
       [ 9.88477615],
       [ 5.4416833 ],
       [19.21742511],
       [23.75708442],
       [20.58883735],
       [13.42394177],
       [21.55333484],
       [15.26956559],
       [16.39975713],
       [15.01157409],
       [ 8.69170234],
       [19.34985503],
       [10

In [38]:
rscore = r2_score(y_test,y_pred)
rscore

0.9052920229772857

In [1]:
from sklearn.linear_model import Lasso, Ridge

In [8]:
lasso = Lasso()

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(r"C:\Users\DeLL\Documents\Python Files\Stats and ML by Garvit\ML\Linear Regression\Linear Regression\Advertising.csv",index_col=0)
df.head()

TV  Radio  Newspaper  Sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [5]:
from sklearn.model_selection import GridSearchCV

In [6]:
from sklearn.model_selection import train_test_split
x = df.drop('Sales',axis=1)
y = df['Sales']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [9]:
params = {'alpha' : np.arange(0.1,1,0.1)}
mod_cv = GridSearchCV(lasso,params,cv=10)
mod_cv.fit(x_train,y_train)

GridSearchCV(cv=10, estimator=Lasso(),
             param_grid={'alpha': array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])})

In [10]:
mod_cv.best_score_

0.7960540143621725

In [11]:
mod_cv.best_params_

{'alpha': 0.9}

In [12]:
ridge = Ridge()